include:
  - project: rdbioseq/cicd
    file: cicd.yml
    inputs:
      module-name: "freq-motif-fastq"
      cd-branch: "main"

stages: 
  - deploy

deploy:
  stage: deploy
  extends: .deploy

deploy-futur:
  stage: deploy
  extends: .deploy-futur